### ISSUE TITLE
Lots of temporary files are getting created.

### ISSUE THREAD

**Issue by dhaval-fitkids** [1000ch/gulp-image#13]
Please see snapshots.

When I run it creates lots of folder 

`00099f67-d587-4a28-b488-2cb7ee1c4719		41ed8cf8-4fc1-4cb2-93c5-1c7c7e71306c		7a54b060-a202-4bbc-8254-fc269e30b58a		d67dd2ad-db7f-42aa-bbe2-f76b7569b816
01548f6b-695d-4c13-8523-9544058fd8bc		42011619-9957-473e-91cb-914c1f9a1925		7e03b06b-d018-4654-befe-c309672ec6ea		d684a64e-0d8f-4372-85b3-85eeef032b41
060b81da-f4b9-4d02-9e8c-2125c692a394		4244c9ad-27c8-40fb-a3e9-5aa27ae981c4		7e4208cb-b5b1-479f-8671-8c69c8bc4a9d		d6dad8e0-ffb3-4eb1-8662-7daad86c7ab5
0b4fe47d-78c5-4422-ab36-71b575764691		430c802c-730b-4fc5-af08-625a96a0c93d		7f181495-1306-453d-89df-f0ab5ebce48e		d8a5396c-a574-4922-934b-76f66aaecebb
0b62ac0a-8fef-4e45-a549-f590976d766c		462d0e5b-b9b7-4627-8872-f23682560c76		812e8f3d-7280-4ac8-bee5-34a22ff47a4a		d8ea7bdd-d23e-4197-a18d-6d7eedb121d0
0c748e3f-ec99-4491-935b-c16222eb8a65		48b97430-fbf5-49c7-bba4-ed078abcc204		8773e1ae-f655-4144-800d-d9bd6b8a04fc		dad7c443-c77d-4e5f-92c8-f337c4bb9960
0c8071c8-860e-40d8-ab14-c9d63c90d81f		493f5b6d-e0a0-4a7f-82e1-7545ea5e4063		88454eb7-c7cd-49f9-b786-06b81ef79eab		dd474191-a37b-49a1-8237-d6f3d0056ca9
0eedacff-45ae-4ceb-8f9c-3ed9c09e248d		49d2f09a-0077-42d2-8302-f7a630ea2052		8c2fbe1f-982c-46b7-9caa-dcdefb56d779		dd594638-8a16-46f4-9d50-1c07163722c2
0fb1d757-5c69-49a1-88a2-c95b8c10ca01	`

`gulp.task('image', function () {
  gulp.src('./app/static/images/**/*.png')
    //.pipe(image()) //todo - is creating many temporary folders, find out why?
    .pipe(gulp.dest('./dist/static/images'));
});`

I am running it in docker container on top of nodejs image.

**Comment by dhaval-fitkids** [comment]
additionally these logs come 

`[11:12:09] - write-text.png -> Cannot improve upon 4.5 KB
[11:12:09] - yellow.png -> Cannot improve upon 14.83 KB
[11:12:09] - student/excel-file-icon.png -> Cannot improve upon 2.4 KB
 [11:12:09] - student/pdf-file-icon.png -> Cannot improve upon 2.32 KB
 [11:12:09] - student/word-file-icon.png -> Cannot improve upon 2.45 KB`

**Comment by luoage** [comment]
I have the same errors

**Comment by 1000ch** [comment]
Still occur in `v2.2.0`?
