### ISSUE TITLE
error after updating dependencies

### ISSUE THREAD

**Issue by Maksim-Methed** [1000ch/gulp-image#136]
npm i -D gulp-image

npm ERR! code 1
npm ERR! path D:\methed-project-web\06-bonus\06-gulp-final\node_modules\gulp-image\node_modules\gifsicle
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! compiling from source
npm ERR! Response code 404 (Not Found)
npm ERR! gifsicle pre-build test failed
npm ERR! Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
npm ERR! "autoreconf" �� ���� ����७��� ��� ���譥�
npm ERR! ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
npm ERR!
npm ERR!
npm ERR!     at D:\methed-project-web\06-bonus\06-gulp-final\node_modules\execa\index.js:231:11
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR!     at async Promise.all (index 0)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Quper\AppData\Local\npm-cache\_logs\2021-11-23T18_21_49_179Z-debug.log

log
[2021-11-23T18_21_49_179Z-debug.log](https://github.com/1000ch/gulp-image/files/7590285/2021-11-23T18_21_49_179Z-debug.log)

**Comment by 1000ch** [comment]
Please try to install the newest version of gulp-image, thanks!
