### ISSUE TITLE
Files with .jpg extension breaking gulp task

### ISSUE THREAD

**Issue by nlenkowski** [1000ch/gulp-image#15]
Gulp-image is working great, however when passing **.jpg** images the task breaks and no images are output. When passing **.jpeg** images it works great. Is this a known limitation or a bug, or perhaps an issue with my configuration?

**package.json**
```
"gulp": "^3.9.1",
"gulp-image": "^2.0.1"
```

**gulpfile.js**
```
var image = require('gulp-image');

gulp.task('images', function() {
    return gulp.src(paths.assets + 'images/**/*.+(png|jpg|gif|jpeg)')
        .pipe(image())
        .pipe(gulp.dest(paths.dist + 'images'));
});
```

I'm on OS X 10.11.5 running node v6.2.2.

**Comment by 1000ch** [comment]
@nlenkowski Would you try with `v2.1.0`?

**Comment by nlenkowski** [comment]
Hey @1000ch, sorry for not responding sooner. Here's a quick test I did of various image types:

![image](https://cloud.githubusercontent.com/assets/1290235/18582924/e2d2eb8e-7c07-11e6-8bd3-5c5b984377bb.png)

I can confirm this issue is resolved, thanks a lot for looking into it and for continuing to maintain gulp-image.
