### ISSUE TITLE
Performance when optimizing hundreds of images

### ISSUE THREAD

**Issue by anagio** [1000ch/gulp-image#19]
I'm running a task which loads a folder with a few sub folders. Total images is around 900~. My settings are to optimize only `png` files. As soon as the task start to run and begins optimizing images my CPU/Memory seems to sky rocket and my machine freezes. I have 16gb on this machine so wouldn't think that's a problem. Is there anyway to set images to be processed in batches?

**Comment by 1000ch** [comment]
@anagio 

Added `concurrent` option to limit the max concurrency in execution. Try `v2.5.0`?

```javascript
gulp.task('image', function () {
  gulp.src('./fixtures/*')
    .pipe(image({
      concurrent: 10
    }))
    .pipe(gulp.dest('./dest'));
});
```

**Comment by anagio** [comment]
@1000ch thanks that options is helping
