### ISSUE TITLE
Task silently fails

### ISSUE THREAD

**Issue by jhulst** [1000ch/gulp-image#22]
The task seems to be failing on some images which then stops processing all further images. There is no error output in the console, the last line is gulp-image reporting on the previous file. 

When it fails, the gulp task stops processing anything further and is marked as completed successfully (the deploy job which is supposed to run after the build never even starts but there is a success code returned from gulp). I'm seeing this when using both svgo and pngquant plugins.

Not really anything useful in the logs but here's what it looks like when it fails:

`[15:13:47] ✔ myparish/promohd.png -> before=638.83 KB after=365.09 KB reduced=273.75 KB(42.9%)
[15:15:56] ✔ cartlogic/promo.png -> before=1.25 MB after=525.74 KB reduced=759.36 KB(59.1%)
➜  ml_web git:(develop) ✗
`

**Comment by GJ2511** [comment]
@jhulst 

I am facing the same problem but only in **Window** and **Mac** Env.
I think task fails when we have some recursive folders ......

Do you also have recursive folders structure??

**Comment by jhulst** [comment]
@GJ2511 By recursive folders do you mean nested folders? If so, yes, my project has nested folders. This is failing on my Mac, haven't tried it on any other platforms.

**Comment by GJ2511** [comment]
@jhulst  yes, exactly

**Comment by MohammedAmine** [comment]
I have the same problem. It doesn't process nested folders. Windows 10 env.

**Comment by vladimirlukyanov** [comment]
Same problem – author not replying ...

**Comment by 1000ch** [comment]
Confirm that your setting choose images with `gulp.src()` which accepts string as glob.

```js
const gulp = require('gulp');
const debug = require('gulp-debug');

gulp.task('image', () => {
  gulp.src([your setting])
    .pipe(debug());
});
```

**Comment by vladimirlukyanov** [comment]
@1000ch, thanks for reply
I'm using following config:

`const gulp = require('gulp');
const image = require('gulp-image');
const debug = require('gulp-debug');


gulp.task('image', () => {
  gulp.src('/var/www/localhost/wp-content/uploads/**.*')
    .pipe(debug());
});

gulp.task('default', ['image']);`

**Comment by 1000ch** [comment]
Try changing `gulp.src('/var/www/localhost/wp-content/uploads/**.*')` `gulp.src('/var/www/localhost/wp-content/uploads/**/*.{png,gif,jpg,svg}')` ?

**Comment by chicagoing** [comment]
I had the same issue and added `gulp-plumber` to troubleshoot.

From zopfli, this was the error I was getting:
https://github.com/google/zopfli/issues/32

Is zopflipng-bin outdated? https://github.com/imagemin/zopflipng-bin/issues/6

But I had issues with mozjpeg and jpegoptim:
```
Message:
    Command failed: /Users/emadison/Projects/website-3/node_modules/mozjpeg/vendor/cjpeg -optimize -progressive
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/emadison/Projects/website-3/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

Details:
    code: null
    killed: false
    stdout:
    stderr: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/emadison/Projects/website-3/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found
```

```
Message:
    Command failed: /Users/emadison/Projects/website-3/node_modules/jpegoptim-bin/vendor/jpegoptim --strip-all --strip-iptc --strip-icc --stdin --stdout
dyld: Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /Users/emadison/Projects/website-3/node_modules/jpegoptim-bin/vendor/jpegoptim
  Reason: image not found

Details:
    code: null
    killed: false
    stdout:
    stderr: dyld: Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /Users/emadison/Projects/website-3/node_modules/jpegoptim-bin/vendor/jpegoptim
  Reason: image not found
```

Only pngquant and jpegRecompress work for me.

**Comment by 1000ch** [comment]
[jpegoptim](https://github.com/tjko/jpegoptim) installation required by gulp-image seems to be failed. Would you try to re-install jpegoptim-bin after installing correct version libjpeg-turbo instructed on jpegoptim's readme?

> REQUIREMENTS
>	Independent JPEG Group's jpeg library (libjpeg) version 6b or later.
>	(Alternatively should also work with libjpeg-turbo or mozjpeg)

**Comment by 1000ch** [comment]
Move to #30
