### ISSUE TITLE
Task skips some files

### ISSUE THREAD

**Issue by aalyokhin** [1000ch/gulp-image#24]
Hi. Thanks for a great plugin.
However, I have faced with the following issue - for some reason some files are just being skipped. Task code:

```
gulp.task('images', function() {  
  return gulp.src(paths.img + '**/*')  
    .pipe(image({  
      concurrent: 10  
    }))  
    .pipe(gulp.dest('./assets/images'));  
});
```

It works great, but simply not processing more than a half of files. If I remove `concurrent: 10` parameter, I get an error:

> (node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit. 

and after that only some files are processed, even less than with parameter. 

I have tried to wrap `image()` call with cache plugin, like this `cache(image())`, it worked, but optimization level is very very slight, like 5% or something.

Could you please help me with this? Thanks in advance.

**Comment by VenPixel** [comment]
Seeing the same issue. Most images get processed but some seem to just be completely ignored. See below for sample code:


`

     return gulp.src(IMG_SRC)
                .pipe(image({
                        optimizationLevel: 5,
                        progressive: true,
                        interlaced: true,
                        pngquant: true,
                        jpegoptim: true,
                        optipng: true,
                        zopflipng: true,
                        gifsicle: true,
                        concurrent: 10
                }))
                .pipe(gulp.dest(IMG_DEST));

`

And IMG_SRC is defined as follows:
`
var IMG_SRC = ['../images/*.png', '../images/services/*.png', '../images/clients/*.png'];
`

Any help tracking down what is causing this would be greatly appreciated.

**Comment by cyChop** [comment]
Great plugin indeed!

I have the same problem as above (I configured it by copying the default options proposed in the README). One more piece of intel: if I decrease the value of `concurrent`, less files seem to be processed.

If I remove it altogether, more (but not all) are processed, but I too see the warning @aalyokhin mentioned:

> (node:8808) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit

(running on Windows 10 w/ Node 6.9)

**Comment by 1000ch** [comment]
Would you try to decrease the value of `concurrent`?

**Comment by csleong98** [comment]
still facing the same thing though. I try not passing any object and it will only still optimised some files (the same files that was optimised)

**Comment by csleong98** [comment]
it is doing ok now if i don't add anything and just use the sample code given in the documentation

**Comment by ajfick** [comment]
I'm also experiencing this issue. It seems to always skip the same files, however changing `concurrent` has not made a difference in my case. There is no information that is logged for these images. 
Running on WSL w/ Node v10.13

**Comment by 1000ch** [comment]
Now `gulp-image` output three kinds of a log:

1. "Optimization is skipped" when the file size is the same before/after optimization
2. "Cannot improve upon" when the file size is bigger than before optimization
3. "Optimized" log when the file size is reduced as we expect

If still some files are skilled other than those, it might be an unexpected/unhandled exception. Please report again then.
