### ISSUE TITLE
Type of optimization and limit on file size

### ISSUE THREAD

**Issue by fernandofas** [1000ch/gulp-image#26]
Hi there,

This plugin is excellent and works well when the configuration is correct.

I have 2 question about it.

1- What type of optimization is used to compress the images?

2- Is there any limit on file size when running the plugin on gulp?

The first question is because I'm comparing the optimization with Kraken and on large file sizes there are still quite a bit to compress.

Kind regards,

Fernando Fas

**Comment by 1000ch** [comment]
> 1- What type of optimization is used to compress the images?

See [dependencies](https://github.com/1000ch/gulp-image/blob/master/package.json) and [parameters](https://github.com/1000ch/gulp-image/blob/master/optimize.js) for optimization.

> 2- Is there any limit on file size when running the plugin on gulp?

As your machine I/O allows.
