### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by marcosvrs** [1000ch/gulp-image#29]
Version: gulp-image@2.7.6

When trying to compress this image: https://unsplash.com/photos/XJXWbfSo2f0
(File size: 20.505KB)
I have this error:
`(node:10064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error in plugin 'gulp-image'
Message:
    stdout maxBuffer exceeded
Details:
    stream: stdout
(node:10064) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by maksymdavydchuk** [comment]
I have the same issue with large files

**Comment by ovod88** [comment]
Hello.
The same issue. Any updates on this?

**Comment by maksymdavydchuk** [comment]
Привет, не удалось решить проблему. Использую
https://www.npmjs.com/package/gulp-tinypng-nokey/

2017-08-31 16:06 GMT+03:00 Volodymyr Khrystenko <notifications@github.com>:

**Comment by 1000ch** [comment]
Would you try `v3.0.0`?

**Comment by 1000ch** [comment]
Closing. Re-open this if anyone encountered same issue.
