### ISSUE TITLE
Install of Guetzli error

### ISSUE THREAD

**Issue by ecDusty** [1000ch/gulp-image#37]
A great gulp plug-in. I've used it a-lot over the last 2 years.

Just running into this issue after I've tried to start using gulp-image of the last week. There is to be an error for  Guetzli, not installing correctly

I've tried completely removing all gulp file and reinstalling. Even completely removing NPM and gulp, then re-installing. Still getting the error.

I'm running a Windows 10 machine. Please see the error below:
![image](https://user-images.githubusercontent.com/10532613/32707792-4a2d1556-c861-11e7-84aa-4f08bb5e1147.png)

All other parts of gulp-image install without issue.

Keep up the great work!

**Comment by azorath** [comment]
this is still an issue 😞

**Comment by ecDusty** [comment]
Yeah still no news about a fix. Still using this as it's my favorite Image optimizer with gulp.
