### ISSUE TITLE
JPGs are not compressed 

### ISSUE THREAD

**Issue by davide2894** [1000ch/gulp-image#41]
Hello, before opening this issue I read other ones that were closed, like [#8](https://github.com/1000ch/gulp-image/issues/8), and tried the fixes suggested. Unfortunately, I couldn't solve my problem.

gulp-image` is compressing png files without any flaw but when it comes to the jpg format, it leaves them as they are. If it is of any help, here it is my configuration:

```
var gulp = require('gulp');
var image = require("gulp-image");
var imagemin = require('gulp-imagemin');
var jpegRecompress = require("imagemin-jpeg-recompress");
var mozjpeg = require("imagemin-mozjpeg");
var jpegoptim = require('jpegoptim-bin');


// Optimization tasks
// -------------------

gulp.task("images:minify", function () {
    return gulp.src("images_src/**/*")
        .pipe(imagemin([imageminMozJpeg()], {
            verbose: true
        }))
        .pipe(gulp.dest("images_src/compressed"));
});

gulp.task("images:compress", function () {
    gulp.src("images_src/**/*.*")
    .pipe(image({
        jpegRecompress: true,
        jpegoptim: false,
        mozjpeg: true,
        concurrent: 10
    }))
    .pipe(gulp.dest("tmp"));
})
```
And here's what the terminal outputs when I try to run the task
![screenshot from 2018-01-04 12-39-03](https://user-images.githubusercontent.com/26111923/34561926-64f15fd2-f14c-11e7-9bfd-d76c72a2c48d.png)

Could you please help me?

**Comment by dbaronov** [comment]
Hello,
I have this setup here:

```
	.pipe(image({
		pngquant: true,
		optipng: false,
		zopflipng: false,
		jpegRecompress: true,
		mozjpeg: false,
		guetzli: false,
		gifsicle: false,
		svgo: true,
		concurrent: 10
	}))
```

The idea is you should only use one tool to compress each type of image. So in your case the setup should look like this:

```
    .pipe(image({
        jpegRecompress: true,
        jpegoptim: false,
        mozjpeg: false,
        concurrent: 10
    }))
```

Let us know if this helps.

**Comment by 1000ch** [comment]
If `gulp-image` works correctly, JPG files are already optimized (`gulp-image` does not override images if applied images are bigger than not applied).
