### ISSUE TITLE
Regression from version 4.1.0 to 4.2.0, install failing at mozjpeg

### ISSUE THREAD

**Issue by Siilwyn** [1000ch/gulp-image#42]
Version 4.1.0 installs and works perfectly. :1st_place_medal: 

However trying to install version 4.2.0 on Linux (Ubuntu 16.04) results in the following error:
```
Message:
    Command failed: /home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor/cjpeg -optimize -progressive -outfile /tmp/0ae2c407-8250-4d25-8755-282aa9542763 /tmp/80d2c3e1-7f29-4ab1-bd73-a4259606b36d
/home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory


Details:
    code: 127
    killed: false
    stdout: 
    stderr: /home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

    failed: true
    signal: null
    cmd: /home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor/cjpeg -optimize -progressive -outfile /tmp/0ae2c407-8250-4d25-8755-282aa9542763 /tmp/80d2c3e1-7f29-4ab1-bd73-a4259606b36d
    timedOut: false
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by alexthegoodman** [comment]
[22:35:36] Error in plugin 'gulp-image'
Message:
    Command failed: /Applications/MAMP/bin/mamp/www/xxx/node_modules/zopflipng-bin/vendor/zopflipng -y --lossy_8bit --lossy_transparent /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/3724bf5e-c737-4264-93c2-0b389fd82d66 /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/4fd6c224-b226-4d80-82ad-2c9fc55062ab

Optimizing /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/3724bf5e-c737-4264-93c2-0b389fd82d66
Encoding error 82: color conversion to palette requested while a color isn't in palette
Decoding error 82: color conversion to palette requested while a color isn't in palette
There was an error


Details:
    code: 1
    killed: false
    stdout: Optimizing /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/3724bf5e-c737-4264-93c2-0b389fd82d66
Encoding error 82: color conversion to palette requested while a color isn't in palette
Decoding error 82: color conversion to palette requested while a color isn't in palette
There was an error


    stderr: 
    failed: true
    signal: null
    cmd: /Applications/MAMP/bin/mamp/www/xxx/node_modules/zopflipng-bin/vendor/zopflipng -y --lossy_8bit --lossy_transparent /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/3724bf5e-c737-4264-93c2-0b389fd82d66 /private/var/folders/1s/rlv25pzd2l526kccg_2c0d5c0000gn/T/4fd6c224-b226-4d80-82ad-2c9fc55062ab
    timedOut: false
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

**Comment by 1000ch** [comment]
Is libpng installed? If not, try `apt-get install libpng-dev`.

**Comment by Siilwyn** [comment]
@1000ch after installing that it does give a different error message:
```
  ⚠ The `/home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor" --bindir="/home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor" --libdir="/home/siilwyn/codeground/selwyn.cc/node_modules/mozjpeg/vendor" && make -j8 && make install -j8
Command failed: autoreconf -fiv
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

If 4.2.0 introduces new dependencies it should've been a major. Besides that the instructions in the readme: `apt-get install -y libjpeg libpng` don't work, both packages are unable to locate. That said, version 4.1.0 of this modules is still working fine.

**Comment by Siilwyn** [comment]
Update with 4.3.0 the error message is:
```
Details:
    code: 127
    killed: false
    stdout: 
    stderr: /home/siilwyn/codeground/selwyn.cc/node_modules/gulp-image/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

    failed: true
    signal: null
    cmd: /home/siilwyn/codeground/selwyn.cc/node_modules/gulp-image/node_modules/mozjpeg/vendor/cjpeg -optimize -progressive -outfile /tmp/10909298-54ea-4f56-b725-33eafdc1a40e /tmp/7b79c538-14d3-4526-ba70-68e7bbe20ad2
    timedOut: false
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

```

**Comment by timogoosenwork** [comment]
See this it might help: https://stackoverflow.com/questions/48948053/error-while-loading-shared-libraries-libpng16-so-16
 This should solve the issue:

```# apt-get install libpng16-dev```

**Comment by Siilwyn** [comment]
Thank you @timogoosenwork that fixed it!

**Comment by morganestes** [comment]
For anyone else searching here,  if`libpng16` isn't available on your distribution (I'm using Debian 8/jessie), you'll need to build it yourself. I'm using a Docker image for deploys, so I installed it with these commands:

```
# Install dependencies for gulp-image
RUN apt-get update -q \
	&& apt-get install -qy libjpeg-dev \
	&& curl -L https://sourceforge.net/projects/libpng/files/libpng16/1.6.35/libpng-1.6.35.tar.gz/download > libpng-1.6.35.tar.gz \
	&& tar -xzvf libpng-1.6.35.tar.gz \
	&& cd libpng-1.6.35 \
	&& ./configure \
	&& make \
	&& make install \
	&& ldconfig
```
