### ISSUE TITLE
Can't change quality setting for mozjpeg

### ISSUE THREAD

**Issue by MichaelJWallis** [1000ch/gulp-image#47]
I am trying to set quality setting for the mozjpeg module however struggling to do so. According to their documentation the -quality flag can be used with a value from 0 to 100. I am attempting to do something like the below, however I'm not sure if I'm misreading your own documentation and using options incorrectly.

```
.image({
    pngquant: true,
    optipng: false,
    zopflipng: false,
    jpegRecompress: false,
    mozjpeg: true,
    guetzli: false,
    gifsicle: true,
    svgo: true,
    concurrent: 10,
    quiet: true,
    options: {
        mozjpeg: ['-quality', 60],
    }
})
```

**Comment by 1000ch** [comment]
Try this.

```js
.image({
    pngquant: true,
    optipng: false,
    zopflipng: false,
    jpegRecompress: false,
    mozjpeg: ['-quality', 60],
    guetzli: false,
    gifsicle: true,
    svgo: true,
    concurrent: 10,
    quiet: true
})
```

**Comment by MikeyWallis** [comment]
That works great, looks I had the option in the wrong place. Cheers.
