### ISSUE TITLE
Request to remove gulp-util

### ISSUE THREAD

**Issue by ecDusty** [1000ch/gulp-image#51]
Really enjoy this gulp add-on for managing images. But as Gulp is moving to v4, it is getting rid of gulp-util. I see that this plugin is dependent on it:

-- gulp-image@4.3.0
  `-- gifsicle@3.0.4
    `-- bin-build@2.2.0
      `-- download@4.4.3
        `-- gulp-decompress@1.2.0
          `-- gulp-util@3.0.8

A great little walk through article of how to remove gulp-util plug in can be found here:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5#635d

**Comment by 1000ch** [comment]
It's a problem of `download` and related modules, not a problem of this plugin. I'm working on them on imagemin org, so plrease wait 🙏

**Comment by ecDusty** [comment]
Thanks for your great work! Really enjoy the plugin.
