### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by ComahonQQComahon** [1000ch/gulp-image#56]
Hello. I have a file package.json
with code
 `{
  "devDependencies": {
    "autoprefixer": "^9.7.3",
    "browser-sync": "^2.26.7",
    "gulp": "^4.0.2",
    "gulp-image": "^5.1.0",
    "gulp-jshint": "^2.1.0",
    "gulp-newer": "^1.4.0",
    "gulp-postcss": "^8.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "jshint": "^2.10.3"
  }
}
`

Everything installs correctly with npm install cammand, except 'gulp-image'

the following error appears:

http://joxi.ru/5md5dW0fevoMP2

http://joxi.ru/L2149jvUg6Qpkm

http://joxi.ru/RmzN9gecRWkz9m

installed ver. of nodejs is 12.13.1
gulp ver. 4.0.2

Tell me what could be the problem? thank you

**Comment by 1000ch** [comment]
Please try to install the newest version.
