### ISSUE TITLE
withMetadata

### ISSUE THREAD

**Issue by cemfirat** [1000ch/gulp-image#59]
An option for controlling MetaData would be very good. Is there a possibility?

**Comment by 1000ch** [comment]
You can control image metadata by passing options for each plugin as mentioned on [usage section](https://github.com/1000ch/gulp-image#usage). But, if these bundled plugins don't have functionalities to manage image metadata as you want, it is impossible.

**Comment by cemfirat** [comment]
thanks!

**Comment by cemfirat** [comment]
what does -y mean?

**Comment by 1000ch** [comment]
Yes.
