### ISSUE TITLE
PNG

### ISSUE THREAD

**Issue by GurovDmitriy** [1000ch/gulp-image#79]
what parameters should i adjust to increase the png compression.

Thanks!

**Comment by 1000ch** [comment]
Please configure options for `gulp-image` as [usage section](https://github.com/1000ch/gulp-image#usage). For PNG, you will need to configure options of [optipng](http://optipng.sourceforge.net/), [pngquant](https://pngquant.org/), and [zopflipng](https://github.com/google/zopfli/blob/master/README.zopflipng).
