### ISSUE TITLE
JPEG files are not being compressed

### ISSUE THREAD

**Issue by woltoe** [1000ch/gulp-image#8]
Plugin works well except when I'm trying to affect my jpg files. Please, answer, as soon as possible. Thanks.
![screen shot 2015-09-25 at 22 54 28](https://cloud.githubusercontent.com/assets/13152822/10111152/b3a3acfe-63da-11e5-8d94-88aedceac59c.png)

**Comment by woltoe** [comment]
Log, that I've obtained, when reinstalled the plugin.
![screen shot 2015-09-25 at 23 17 38](https://cloud.githubusercontent.com/assets/13152822/10111301/c83750a2-63db-11e5-931a-596f2eb85ed8.png)

**Comment by 1000ch** [comment]
I guess they are already optimized.
Or optimizers for JPEG are not working well on your environment.
Can you install `jpegoptim-bin` to anywhere on your PC?

**Comment by woltoe** [comment]
I apologize for opening issue. The problem was about conflict ```jpegoptim``` in OS X 10.10.5 (i guess).
Problem was solved after manual re-installing ```jpegoptim``` through ```brew```.
Now plugin works pretty well.

**Comment by 1000ch** [comment]
No problem (´･ω･`)b

**Comment by davide2894** [comment]
Hello, I didn't want to create another issue as I though writing here would had more sense. Please let me know if you're ok with it.

I tried what you suggested but unfortunately it didn't work. `gulp-image` is compressing png without any flaw but when it comes to jpg, it leaves them as they are. If it is of any help, here it is my configuration:

```
var gulp = require('gulp');
var image = require("gulp-image");
var imagemin = require('gulp-imagemin');
var jpegRecompress = require("imagemin-jpeg-recompress");
var mozjpeg = require("imagemin-mozjpeg");
var jpegoptim = require('jpegoptim-bin');


// Optimization tasks
// -------------------

gulp.task("images:minify", function () {
    return gulp.src("images_src/**/*")
        .pipe(imagemin([imageminMozJpeg()], {
            verbose: true
        }))
        .pipe(gulp.dest("images_src/compressed"));
});

gulp.task("images:compress", function () {
    gulp.src("images_src/**/*.*")
    .pipe(image({
        jpegRecompress: true,
        jpegoptim: false,
        mozjpeg: true,
        concurrent: 10
    }))
    .pipe(gulp.dest("tmp"));
})
```
And here's what the terminal outputs when I try to run the task
![screenshot from 2018-01-04 12-39-03](https://user-images.githubusercontent.com/26111923/34561926-64f15fd2-f14c-11e7-9bfd-d76c72a2c48d.png)

Could you help me please?
